import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function slugify(s) {
  return String(s || 'lecture').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'lecture';
}

export function buildManimProject({ topic = 'Obsidian notes for learning', outputRoot = '/tmp/pi-gnosis/manim', write = false } = {}) {
  const slug = slugify(topic);
  const projectRoot = resolve(outputRoot, slug);
  const sceneSpec = {
    topic,
    scenes: [
      {
        className: 'TemporarySurface',
        learningGoal: 'Show that the generated video is temporary and the notes are what the learner keeps.',
        visualMetaphor: 'One disposable screen fading into a notebook page',
        durationSeconds: 25,
      },
      {
        className: 'ObsidianPage',
        learningGoal: 'Show how prompts, blanks, corrections, and reflections become durable notes.',
        visualMetaphor: 'A note page with fill-in blanks and linked sections',
        durationSeconds: 35,
      },
    ],
  };
  const plan = `# ${topic}\n\nNarrative arc: start with a temporary visual explanation, then show how the learner keeps the durable notes in Obsidian while the generated video stays disposable.\n\nAha moment: the teaching surface is temporary; the learning surface is the note the learner keeps.\n`;
  const script = `from manim import *\n\n\nclass TemporarySurface(Scene):\n    def construct(self):\n        title = Text("Pi-GNOSIS", font_size=42)\n        subtitle = Text("temporary video -> durable notes", font_size=28).next_to(title, DOWN)\n        self.play(Write(title))\n        self.play(FadeIn(subtitle))\n        self.wait(1)\n\n\nclass ObsidianPage(Scene):\n    def construct(self):\n        page = RoundedRectangle(corner_radius=0.2, width=8.5, height=4.8)\n        header = Text("Obsidian note", font_size=30).move_to(page.get_top() + DOWN * 0.5)\n        blanks = VGroup(\n            Text("Define the concept: ________", font_size=24),\n            Text("Mistake I made: ________", font_size=24),\n            Text("Checkpoint: ________", font_size=24),\n        ).arrange(DOWN, aligned_edge=LEFT, buff=0.45).move_to(page.get_center()).shift(DOWN * 0.2)\n        self.play(Create(page), Write(header))\n        self.play(Write(blanks))\n        self.wait(1)\n`;
  const render = '#!/usr/bin/env bash\nset -euo pipefail\nmanim -ql script.py TemporarySurface ObsidianPage\n';
  const readme = `# ${topic}\n\nGenerated by Pi-GNOSIS. Run \`./render.sh\` after installing Manim CE, ffmpeg, and LaTeX if needed.\n`;
  const files = {
    'plan.md': plan,
    'scene_spec.json': JSON.stringify(sceneSpec, null, 2) + '\n',
    'script.py': script,
    'render.sh': render,
    'README.md': readme,
  };
  if (write) {
    mkdirSync(projectRoot, { recursive: true });
    for (const [name, content] of Object.entries(files)) writeFileSync(resolve(projectRoot, name), content, 'utf8');
  }
  return { projectRoot, files };
}
