import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function slugify(s) {
  return String(s || 'lecture').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'lecture';
}

export function buildManimProject({ topic = 'knowledge tracing DAGs', outputRoot = 'manim', write = false } = {}) {
  const slug = slugify(topic);
  const projectRoot = resolve(outputRoot, slug);
  const sceneSpec = {
    topic,
    scenes: [
      {
        className: 'OpeningMap',
        learningGoal: 'Show that Pi-GNOSIS separates conversation, Circuitry programs, DAG state, and notes.',
        visualMetaphor: 'Four labeled boxes connected by arrows',
        durationSeconds: 25,
      },
      {
        className: 'KTDagScene',
        learningGoal: 'Show why learner state is a graph rather than a checklist.',
        visualMetaphor: 'Concept nodes with prerequisite and misconception edges',
        durationSeconds: 35,
      },
    ],
  };
  const plan = `# ${topic}\n\nNarrative arc: start with one Pi conversation, reveal delegated Circuitry graph programs, then show how evidence updates a KT DAG while Obsidian stays human-readable.\n\nAha moment: the graph is not just notes; it is executable state for tutoring decisions.\n`;
  const script = `from manim import *\n\n\nclass OpeningMap(Scene):\n    def construct(self):\n        title = Text(\"Pi-GNOSIS\", font_size=42)\n        subtitle = Text(\"conversation -> Circuitry -> state -> notes\", font_size=28).next_to(title, DOWN)\n        self.play(Write(title))\n        self.play(FadeIn(subtitle))\n        self.wait(1)\n\n\nclass KTDagScene(Scene):\n    def construct(self):\n        nodes = VGroup(*[Circle(radius=0.35).shift(RIGHT * (i - 1) * 2) for i in range(3)])\n        labels = VGroup(Text(\"A\", font_size=24).move_to(nodes[0]), Text(\"B\", font_size=24).move_to(nodes[1]), Text(\"C\", font_size=24).move_to(nodes[2]))\n        arrows = VGroup(Arrow(nodes[0].get_right(), nodes[1].get_left(), buff=0.1), Arrow(nodes[1].get_right(), nodes[2].get_left(), buff=0.1))\n        caption = Text(\"open-ended evidence updates the DAG\", font_size=28).next_to(nodes, DOWN)\n        self.play(Create(nodes), Write(labels))\n        self.play(Create(arrows))\n        self.play(FadeIn(caption))\n        self.wait(1)\n`;
  const render = '#!/usr/bin/env bash\nset -euo pipefail\nmanim -ql script.py OpeningMap KTDagScene\n';
  const readme = `# ${topic}\n\nGenerated by Pi-GNOSIS. Run \`./render.sh\` after installing Manim CE, ffmpeg, and LaTeX if needed.\n`;
  const files = {
    'plan.md': plan,
    'scene_spec.json': JSON.stringify(sceneSpec, null, 2) + '\n',
    'script.py': script,
    'render.sh': render,
    'README.md': readme,
  };
  if (write) {
    mkdirSync(projectRoot, { recursive: true });
    for (const [name, content] of Object.entries(files)) writeFileSync(resolve(projectRoot, name), content, 'utf8');
  }
  return { projectRoot, files };
}
